#!/bin/bash

orig_dir="$(pwd)"

# Create the $FOAM_USER_LIBBIN if not existing.
# - This happens with a fresh OpenFOAM installation.
# - openfoam-smartsim libraries are placed into $FOAM_USER_LIBBIN
if [ ! -d "$FOAM_USER_LIBBIN" ]; 
then
    mkdir -p $FOAM_USER_LIBBIN
fi

# Set compiler options 
if [ $WM_COMPILER ==  "Gcc" ]; then
    echo "Using gcc and g++" 
    export CC=gcc
    export CXX=g++
elif [ $WM_COMPILER == "Icx" ]; then
    echo "Using icpx"
    export CC=icx-cc
    export CXX=icpx
fi
cd "$_REPO_ROOT" || exit 1

LIB=lib
if [ -d $SMARTREDIS_INSTALL_PATH/lib64/ ]; then
  LIB=lib64
fi
cp $SMARTREDIS_INSTALL_PATH/$LIB/libsmartredis.* $FOAM_USER_LIBBIN 
cp $SMARTREDIS_INSTALL_PATH/$LIB/libhiredis.* $FOAM_USER_LIBBIN
cp $SMARTREDIS_INSTALL_PATH/$LIB/libredis++.* $FOAM_USER_LIBBIN
export FOAM_CODE_TEMPLATES=$_REPO_ROOT/etc/dynamicCode/

## Compile OpenFOAM libs
wmake libso src/fvMotionSolvers/displacementLaplacianNonOrthMotionSolver
wmake libso src/fvMotionSolvers/displacementSmartSimMotionSolver

cd "$orig_dir" || exit 1
